<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/16
 * Time: 15:47
 */

namespace backend\controllers;


use \yii\web\Controller;

class MemberController extends Controller
{
    public function behaviors()
    {
        return [


        ]; // TODO: Change the autogenerated stub
    }

    //显示表单
    public function actionLogin(){

    }

}