<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/10
 * Time: 23:29
 */

namespace backend\models;


use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

class Article extends ActiveRecord
{
    //public $imgFile;
    public $content;
    public $article_status;
//    public $category_name;
    public function rules()
    {
        return[
            [['name','intro','sort','content','status','article_category_id'],'required'],
            //['photo','file','extensions'=>['jpg','png','gif'],'skipOnEmpty'=>true],//skipOnEmpty 字段为空跳过当前验证
            [['photo'],'safe']
        ]; // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'name'=>'文章名称',
            'intro'=>'文章简介',
            'sort'=>'文章排序',
            'status'=>'上架状态',
            'photo'=>'文章头像',
            'content'=>'内容',
            'article_category_id'=>'文章类别'
        ]; // TODO: Change the autogenerated stub
    }
    //显示文章列表
    public function getArticleCategory(){
        return $this->hasOne(Article_category::className(),['id'=>'article_category_id']);
    }
  }










