<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/11
 * Time: 20:40
 */

namespace backend\models;


use yii\db\ActiveRecord;
class Books extends ActiveRecord
{
    public $imgFile;
public function rules()
{
    return [
        [['title','intro'],'required'],
        ['imgFile','file','extensions'=>['jpg','png','gif'],'skipOnEmpty'=>true],//skipOnEmpty 字段为空跳过当前验证
    ];
}
public function attributeLabels()
{
    return[

        'title'=>'图书标题',
        'intro'=>'图书简介',
        'imgFile'=>'图书封面'
    ]; // TODO: Change the autogenerated stub
}

}