<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/10
 * Time: 16:43
 */

namespace backend\models;


use yii\db\ActiveRecord;

class Brand extends ActiveRecord
{
//    public $image;
    //字段列表不能为空
    public function rules()
    {
        return [
            [['name', 'intro', 'sort','status'], 'required'],
            [['intro'], 'string'],
            [['logo'],'safe'],
            [['sort', 'status'], 'integer'],
            [['name'], 'string', 'max' => 50],
//            ['image','file','extensions'=>['jpg','png','gif'],'skipOnEmpty'=>true],//skipOnEmpty 字段为空跳过当前验证
        ];
    }
    //将字段改为中文
    public function attributeLabels()
    {
        return [
            'name'=>'品牌名称',
            'intro'=>'品牌简介',
            'sort'=>'品牌排序',
            'logo'=>'品牌LOGO',
            'status'=>'品牌状态'
        ]; // TODO: Change the autogenerated stub
    }
}