<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/11
 * Time: 13:39
 */

namespace backend\models;


use yii\db\ActiveRecord;

class Classs extends ActiveRecord
{
    public function rules()
    {
        return [
            [['class_name'],'required'],
        ]; // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'class_name'=>'班级名称',
        ]; // TODO: Change the autogenerated stub
    }

}