<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/14
 * Time: 21:53
 */

namespace backend\models;


use yii\db\ActiveRecord;

class Goods_gallery extends ActiveRecord
{

    public function rules()
    {
        return [
            [['path'],'required']

        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return[
            'path'=>'图片'
        ]; // TODO: Change the autogenerated stub
    }
}