<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/14
 * Time: 14:40
 */

namespace backend\models;


use yii\db\ActiveRecord;

class Goods_day_count extends ActiveRecord
{
    public function rules()
    {
        return [
            [['count'],'required']

        ]; // TODO: Change the autogenerated stub
    }
}