<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/14
 * Time: 14:41
 */

namespace backend\models;


use yii\db\ActiveRecord;

class Goods_intro extends ActiveRecord
{
    //验证
    public function rules()
    {
        return [
            [['content'],'required']
        ]; // TODO: Change the autogenerated stub
    }

    //设置中文
    public function attributeLabels()
    {
        return [
            'content'=>'简介',
        ]; // TODO: Change the autogenerated stub
    }
}