<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/17
 * Time: 12:54
 */

namespace backend\models;


use yii\base\Model;

class Login extends Model
{
    //定义常量场景
//    const SCENARIO_LOGIN = 'login';
//,'on'=>[self::SCENARIO_LOGIN]
    public $password;
    public $username;
    public $code;
    public $remember;

    public function rules()
    {
        return [
            [['username','password'],'required'],
            ['code','captcha','captchaAction' => 'admin/captcha'],//指定控制器里面的captcha方法
            ['remember','safe'],//这个字段是安全的，不需要验证
        ];
    }
    public function attributeLabels()
    {
        return [
            'username'=>'用户名',
            'password'=>'用户密码',
            'code'=>'验证码',
            'remember'=>'是否记住密码',
        ]; // TODO: Change the autogenerated stub
    }
}