<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/20
 * Time: 11:25
 */

namespace backend\models;


use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

class Menu extends ActiveRecord
{
    const SCENARIO_ADD = 'add';
    public function rules()
    {
        return[
            [['name','sort','url'],'required'],
            [['parent_id'],'safe'],
        [['name','url'],'check','on'=>[self::SCENARIO_ADD]]
        ]; // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'name'=>'添加菜单',
            'sort'=>'排序',
            'url'=>'路由',
            'parent_id'=>'菜单名'
        ]; // TODO: Change the autogenerated stub
    }
    //添加显示路由
    public static function getPermissions(){
        //获取所有路由
        $permission = \yii::$app->authManager->getPermissions();
        return array_merge([0=>'=请选择路由='],ArrayHelper::map($permission,'name','name'));
    }
    //显示列表
    public static function getMenu(){
        $menus = Menu::find()->all();
        return  ArrayHelper::merge([0=>'顶级菜单'],ArrayHelper::map($menus,'id','name'));
    }
    //菜单健壮型
    public function check()
    {
        $datas = Menu::find()->all();
        foreach ($datas as $data){
            if($data->name===$this->name){
                $this->addError('name','菜单已存在');
            }
            if($data->url==$this->url){
                $this->addError('url','路由已存在');
            }
        }
    }
}