<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/8/18
 * Time: 15:54
 */

namespace backend\models;
use yii\base\Model;
use yii\helpers\ArrayHelper;

class Permission extends Model
{
    public $name;
    public $description;
    public function rules()
    {
        return [
            [['name','description'],'required'],
        ];
    }
    public function attributeLabels()
    {
        return [
            'name'=>'权限名称',
            'description'=>'描述'
        ]; // TODO: Change the autogenerated stub
    }
    //为角色添加权限
    public function save(){
        //实例化authmanger组件
        $authManger = \yii::$app->authManager;
        //获取权限
        if($authManger->getPermission($this->name)){
            $this->addError('name','权限已经存在');
            return false;
        }else{ //创建权限
            $permission = $authManger->createPermission($this->name);
            //为权限添加描述
            $permission->description = $this->description;
            //保存到数据库
            $authManger->add($permission);
            return true;
        }
    }
    public function editPermission($permissionName){
        //实例化组件
        $authManager = \yii::$app->authManager;
        //对应名称得到权限对象
        $permissionObj = \yii::$app->authManager->getPermission($permissionName);
        //对应名称修改数据
        if($permissionObj->name==$this->name){
            //将表单接受数据保存
            $permissionObj->description = $this->description;
            //通过名称修改一条数据
            $authManager->update($permissionName,$permissionObj);
            return true;
        }else{//权限唯一性（如果已存在提示错误信息。）
           if($authManager->getPermission($this->name)){
               $this->addError($this->name,'权限已存在');
               return false;
           }else{
               //否则将权限保存
               $permissionObj->name = $this->name;
               $permissionObj->description = $this->description;
               //修改
               $authManager->update($permissionObj->name,$permissionObj);
               return true;
           }
        }
    }
}